name: Sensor CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    name: Build, Test & Push Sensor Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & run pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r raspberry_pi/requirements.txt pytest
          python -m pytest raspberry_pi/ --cov=raspberry_pi --cov-fail-under=80

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push sensor image
        uses: docker/build-push-action@v4
        with:
          context: ./raspberry_pi
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USER }}/5-final-nopylint-sensor:latest

  deploy:
    name: Deploy Sensor to Droplet
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: SSH & deploy sensor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USER }}/5-final-nopylint-sensor:latest
            docker rm -f pi_sensor || true
            docker run -d --name pi_sensor ${{ secrets.DOCKERHUB_USER }}/5-final-nopylint-sensor:latest
          EOF


