name: Sensor Image CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-push:
    name: 🔧 Build & Push Sensor Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          # 1) Send the whole repo as the build context:
          context: .
          # 2) Point at your existing Dockerfile inside raspberry_pi/
          file:   raspberry_pi/Dockerfile
          push:   true
          tags:   ${{ secrets.DOCKERHUB_USER }}/5-final-nopylint-sensor:latest
