# .github/workflows/sensor-deploy.yml
name: Sensor CD/CI

on:
  push:
    branches: [main]
    paths:
      - 'raspberry_pi/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Log in to DOCR
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: doctl
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Build & push sensor image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t registry.digitalocean.com/nopylint/raspberry_pi:latest \
            --push \
            raspberry_pi
