name: Sensor CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'raspberry_pi/**'
      - '.github/workflows/sensor-ci-cd.yml'

jobs:
  build-and-push:
    name: 🔧 Build & Push Sensor Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push raspberry_pi Image
        uses: docker/build-push-action@v4
        with:
          context: ./raspberry_pi
          file: ./raspberry_pi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/5-final-nopylint-sensor:latest
